### ISSUE TITLE
As soon as I add this dependency my project fails to build

### ISSUE THREAD

**Issue by Zeyad-37** [icerockdev/moko-parcelize#11]
As the title says, as soon as I add moko-parcelize dependency to my project, even though the gradle sync succeeds, I am not able to reference my shared module in any other module anymore. 
Also the documentation says that we need to import the `kotlin-android-extension` plugin, which is deprecated in kotlin 1.4.20 and should be replaced with `kotiln-parcelize`. So could you shed some light on this as well, thanks in advance

**Comment by Alex009** [comment]
@Zeyad-37 show please gradle log from `./gradlew build --info`
also plugin `kotlin-android-extensiond` deprecated but available now, so you should use it while `moko-parcelize` not updated to `kotlin-parcelize`
