### ISSUE TITLE
Migrate to kotlin-parcelize

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-parcelize#12]
kotlin-android-extensions is deprecated from 1.4.20, we should move to kotlin-parcelize

**Comment by nrobi144** [comment]
I'll update this, together with #13

**Comment by Alex009** [comment]
> (I'll update this, together with #13)
> 
> If I'm correct this is fixed with [71f39d6](https://github.com/icerockdev/moko-parcelize/commit/71f39d63cb7fab09adfab1dcae1dd33667e1f266), @Alex009 right?

yes, but in this branch used kotlin 1.4.30-M1. it can't be released now :)

**Comment by nrobi144** [comment]
I see, I'll update it to latest stable release version
