### ISSUE TITLE
Task compileKotlinIosX64 failed with 0.6.0 moko-parcelize version

### ISSUE THREAD

**Issue by ATchernov** [icerockdev/moko-parcelize#19]
`
e: Compilation failed: Deserializer for declaration public dev.icerock.moko.parcelize/Parcelize.<init>|-5645683436151566731[0] is not found

 * Source files: MR.kt, MR.kt, AuthFactotyImpl.kt, SharedFactory.kt
 * Compiler version info: Konan: 1.4.21 / Kotlin: 1.4.21
 * Output kind: LIBRARY

e: java.lang.IllegalStateException: Deserializer for declaration public dev.icerock.moko.parcelize/Parcelize.<init>|-5645683436151566731[0] is not found
`

Reproduced on moko-boilerplate with version update to "0.6.0" in Deps

**Comment by Alex009** [comment]
start from 0.6.0 we have optional expectation of annotation class, so while all moko dependencies not published with 0.6.0 dependency it will be not compatible. for now use 0.5.0
