### ISSUE TITLE
 Deserializer for declaration public dev.icerock.moko.parcelize.Parcelize.<init> is not found for IOS target

### ISSUE THREAD

**Issue by krottv** [icerockdev/moko-parcelize#23]
This error happens when I run packForXcode

**Comment by Alex009** [comment]
run `~/.gradlew dependencies` and found usages of `moko:parcelize`. you have different versions usage. check what lib use old version and up version of this dependency.
or just update all your moko libs to actual versions - see versions on moko.icerock.dev

**Comment by krottv** [comment]
@Alex009 
I check. Everywhere is used dev.icerock.moko:parcelize-android:{strictly 0.6.1} -> 0.6.1
But no error found if I use 0.5.0

**Comment by Alex009** [comment]
@krottv can you share build config?

**Comment by krottv** [comment]
@Alex009 

`apply plugin: "com.android.library"
apply plugin: "kotlin-multiplatform"
apply plugin: 'kotlinx-serialization'
apply plugin: "kotlin-parcelize"
apply plugin: "dev.icerock.mobile.multiplatform-resources"

android {

    sourceSets {
        main {
            manifest.srcFile "src/androidMain/AndroidManifest.xml"
        }
    }

    configurations {
        create("androidTestApi")
        create("androidTestDebugApi")
        create("androidTestReleaseApi")
        create("testApi")
        create("testDebugApi")
        create("testReleaseApi")
    }

    compileSdkVersion 30
    defaultConfig {
        minSdkVersion min_sdk_version
        targetSdkVersion 30
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
}


kotlin {

    android()

    ios {
        binaries {
            framework {
                baseName = "MusicFeature"
                isStatic = false
            }
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation("dev.icerock.moko:mvvm-core:$moko_mvvm_core_version")
                implementation("dev.icerock.moko:parcelize:$moko_parcelize_version")
                implementation("dev.icerock.moko:graphics:$moko_graphics_version")
                implementation("dev.icerock.moko:resources:$moko_resources_version")

                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinx_serialization_json_version")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version")

                implementation "com.soywiz.korlibs.klock:klock:$klockVersion"

                implementation("io.insert-koin:koin-core:$koin_version")

                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")
                implementation "io.ktor:ktor-client-mock:$ktorVersion"

                implementation(project(":ProjectUtils"))
            }
        }
        androidMain {
            dependencies {
                implementation("io.ktor:ktor-client-okhttp:$ktorVersion")
                implementation("io.ktor:ktor-client-logging:$ktorVersion")

                implementation("io.insert-koin:koin-android:$koin_version")
                //testImplementation "io.insert-koin:koin-test:$koin_version")
            }
        }

        iosMain {
            dependencies {
                implementation("io.ktor:ktor-client-ios:$ktorVersion")
            }
        }
    }
}

multiplatformResources {
    multiplatformResourcesPackage = "app.inspiry.music" // required
    iosBaseLocalizationRegion = "base" // optional, default "en"
    multiplatformResourcesSourceSet = "commonMain"  // optional, default "commonMain"
}

task(packForXcode, type: Sync) {
    group = 'build'
    def mode = System.getenv('CONFIGURATION') ?: 'DEBUG'
    def sdkName = System.getenv('SDK_NAME') ?: 'iphonesimulator'
    def targetName = 'ios' + ((sdkName.startsWith('iphoneos')) ? 'Arm64' : 'X64')
    def framework = kotlin.targets.getByName(targetName).binaries.getFramework(mode)
    inputs.property('mode', mode)
    dependsOn(framework.linkTask)
    def targetDir = new File(buildDir, 'xcode-frameworks')
    from({ framework.outputDirectory })
    into(targetDir)
}
tasks.getByName('build').dependsOn(packForXcode)`

**Comment by Alex009** [comment]
and versions file too please

**Comment by krottv** [comment]
@Alex009 
https://pastebin.com/Q0RSPhFU versions file
