### ISSUE TITLE
JS  Enable IR

### ISSUE THREAD

**Issue by Shabinder** [icerockdev/moko-parcelize#25]
js { /* ... */ } -> js(BOTH) { /* ... */ }

**Comment by Shabinder** [comment]
I will possible make a PR , then one can create a new release

**Comment by Shabinder** [comment]
#26  PR Created , even took the opportunity to bump version to 0.7.0 :upside_down_face: , now a release needs to be made

**Comment by Alex009** [comment]
thanks! we release new version today/tomorrow
