### ISSUE TITLE
Parcelize classes that extends from Other classes

### ISSUE THREAD

**Issue by jorgezim** [icerockdev/moko-parcelize#33]
Hello, I am having issue with classes that extends other classes. The child class has all the fields populated correctly, but the fields in the Parent class are empty. How can I make this work?

Example: 

ParentClass:
@Parcelize
open class SettingsChannelDisplay : Parcelable {
    var outputType: OutputType = OutputType.Output1
    var name: String? = ""
    var registers: Map<Byte, ByteArray> = mapOf()
}

Child Class:
@Parcelize
data class BehaviourLinkSettingsDetailChannelDisplay(
    val masterId: Int? = null,
    val masterName: String? = null,
    val masterRoomId: Int? = null                    // If null, show "available for behaviour link"
) : SettingsChannelDisplay(), Parcelable

Values of SettingsChannelDisplay are always empty

**Comment by Alex009** [comment]
you should override propeties of parent class in child class to got @Parcelize works.

https://stackoverflow.com/questions/48097429/parcelize-annotation-toghether-with-inheritance
